### ISSUE TITLE
Is it nearly impossible to write a Port Forwarder that works?

### ISSUE THREAD

**Issue by pha3z** [jchristn/SimpleTcp#18]
So I wrote a port forwarding application using Simple Tcp.  I test it with a custom client connecting to the port forward app, which forwards packets to a custom server (also for testing).  When the server receives a packet, it echos the data back to the port forward app which relays it back to the originating client app.  This way I can verify that the data receives and comes back as the same data.

It works.  But when I try to use this with real applications (such as Sql client to connect to a Sql Server), I get spotty results.  It half-works but some applications throw errors about unexpected data/messages and other things like that.

**Am I wrong in thinking that port forwarding is as simple as putting a middle-man application in between to 2 endpoints to marshal packets from A to B and from B to A?  Is there something else necessary to make this work?**

**Comment by jchristn** [comment]
Hi @pha3z in *theory* it should work but that's not always the case. I suggest looking into how firewalls that proxy TCP do this. Often they have to do fix ups or use NAT/virtual IPs to emulate the actual client or server to maintain protocol semantics. Some app protocols also are sensitive to placement of TCP segments and which ones have/don't have the PSH flag set (I dealt with this extensively in a past life with WAN acceleration and also with security). The correct answer is you have to test app by app and dig into their protocol semantics to see why it may or may not be working. 

Cheers
Joel

**Comment by pha3z** [comment]
Thanks, Joel.

**Comment by jchristn** [comment]
No problemo. I think doing what you want would demand a transparent TCP proxy, ie even though there is a man in the middle, the proxy listens on the IP of the server, and acts on behalf of the client while emulating the client IP and port. We did this within a product at Cisco and it literally either required a) network configuration gymnastics to handle the routing (ie diverting traffic from its original destination) or b) deployment using an inline bypass card that punted packets to a user space packet processor. That way you can preserve IPs and preserve TCP semantics (ie when there is/isn't a PSH and other flags). 

Another option if protocol dissection isn't of interest would be to build something at the IP layer instead of TCP. That also has challenges and some protocols require fix ups (such as FTP).

**Comment by pha3z** [comment]
Wow.  That is very helpful!  Sounds like its just too involved unless the use case absolutely demands it -- which mine doesn't demand that level.

Thank you, sir!
