### ISSUE TITLE
Delimiter?

### ISSUE THREAD

**Issue by Antwns** [jchristn/SimpleTcp#23]
Hello again! I'm sending multiple strings from my client to my server with different methods(programmatical term)
How can I set the server to recognize where each string message ends? eg: Environment.Newline(); at the end of each string means that there is no string within that request.
Here's my problem visually to make it more clear:
DoLogin(CurrentUser);
RequestUsersList(CurrentUser);
RequestStatus(CurrentUser);
all 3 methods have a Server.Send(string); function in them. If they get called at the aforementioned row what happens is one "big"
Server.Send(DoLogin.string + RequestUsersList.string + RequestStatus.string) command. Essentially all the strings get sent at once.
I tried Thread.Sleep(i); And it doesn't really change anything. I haven't tried asigning the tasks to different threads yet if that's a solution. Thanks in advance and I hope my issue was clear enough! 👍  You guys rock

EDIT: I restructured my client and made it work. However this would still be a nice addition to have!

**Comment by jchristn** [comment]
Hi @Antwns sounds like what you need is framing (see this helpful post from Stephen Cleary: https://blog.stephencleary.com/2009/04/message-framing.html)

SimpleTcp doesn't do framing on its own.  WatsonTcp (https://github.com/jchristn/watsontcp) and EasyTcp (https://github.com/Job79/EasyTcp) both do.  In a nutshell the data you send is wrapped with metadata to indicate to the receiver where a message ends.

An alternative would be to build your own framing layer which is why I also built CavemanTcp ("Caveman" because it's "primitive", see https://github.com/jchristn/cavemantcp).  With something like this, you could build your own state machine, reading and writing a specified number of bytes, whereas SimpleTcp will always try to read the defined buffer size from the socket (and fire an event when it gets *something*).

Glad to see that you have it working per your edit.  I don't plan to add this to SimpleTcp since it's built into other projects (mine and others).  

Something I like about the EasyTcp library published by @job79 which may work well for you is how the library has 'actions' that can be applied as attributes on your methods.  i.e. "if I receive action 'LOGIN', execute this method", and when sending a message, being able to send it with an action's tag.  

If you're planning on a lot of back and forth messaging, you may want to look into something with framing built-in.  

Closing this one out, cheers!
