### ISSUE TITLE
Data receiver terminated

### ISSUE THREAD

**Issue by wimpie3** [jchristn/SimpleTcp#43]
I'm using version 2.2.1.1. When I test my code locally on my own pc, I have no issues at all. As soon as I run it on a server on the internet, there seem to be random disconnects and this turns up in the logs:

[SimpleTcp.Server] data receiver terminated for client xxx.xxx.xxx.xxx:yyyyy

(to be clear: this error doesn't appear locally)

Any advice?

**Comment by jchristn** [comment]
Hello, please disable TCP keepalives and let me know if the problem persists.

```
server.Keepalive.EnableTcpKeepAlives = false;
client.Keepalive.EnableTcpKeepAlives = false;
```

**Comment by wimpie3** [comment]
I had indeed enabled the keep alive. I've removed those lines from the code, everything is running ok now. I suppose this means the default value is "false".

**Comment by jchristn** [comment]
Hi @wimpie3 the unfortunate thing about TCP keepalives is that they are implemented beneath everything I do, and I don't get visibility into how or why they do or don't work.  They're really intended to prevent "stuck" network connections due to a cable being unplugged, etc.  And generally, they end up causing more problems when actually being used.  That's the main reason I disabled them by default.  Cheers, Joel
